name: Spleef
main: ru.boomearo.spleef.Spleef
version: 0.1
author: BoomEaro
description: spleef
api-version: 1.13
depend: [FastAsyncWorldEdit, GameControl, Board]
commands:
  spleef:
    usage: /spleef
    description: spleef